name: build-and-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing dependencies
        run: npm ci
      - name: Building project
        env:
          REACT_APP_REALM_APP_ID: ${{ secrets.REACT_APP_REALM_APP_ID }}
          REACT_APP_MONGO_CLIENT: ${{ secrets.REACT_APP_MONGO_CLIENT }}
          REACT_APP_MONGO_DB: ${{ secrets.REACT_APP_MONGO_DB }}
          REACT_APP_MONGO_COLLECTION: ${{ secrets.REACT_APP_MONGO_COLLECTION }}
          REACT_APP_MONGO_COLLECTION_TRANSLATIONS: ${{ secrets.REACT_APP_MONGO_COLLECTION_TRANSLATIONS }}
          REACT_APP_MONGO_COLLECTION_IMAGES: ${{ secrets.REACT_APP_MONGO_COLLECTION_IMAGES }}
          REACT_APP_INIT_LANGUAGE: ${{ secrets.REACT_APP_INIT_LANGUAGE }}
          run: npm run build --if-present
      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build s3://${{ secrets.AWS_BUCKET_DEPLOY }} --follow-symlinks --delete
      - name: Invalidate cache in Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
